"""empty message

Revision ID: 83058bda46b4
Revises: cd1d6dcf7f28
Create Date: 2021-06-08 15:15:27.293065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83058bda46b4'
down_revision = 'cd1d6dcf7f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('last_changed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'last_changed')
    # ### end Alembic commands ###
