"""empty message

Revision ID: cd1d6dcf7f28
Revises: 11be31a27868
Create Date: 2021-05-29 09:11:10.912274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1d6dcf7f28'
down_revision = '11be31a27868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('quality', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('time_received', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_entry')
    op.drop_table('card')
    # ### end Alembic commands ###
