"""empty message

Revision ID: f348e65273f0
Revises: 
Create Date: 2021-05-25 11:31:24.113400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f348e65273f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_id'),
    sa.UniqueConstraint('sub_id')
    )
    op.create_table('sub_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_change', sa.DateTime(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('prev_name', sa.String(length=128), nullable=False),
    sa.Column('new_name', sa.String(length=128), nullable=False),
    sa.Column('prev_status', sa.Boolean(), nullable=False),
    sa.Column('new_status', sa.Boolean(), nullable=False),
    sa.Column('prev_sub_id', sa.String(length=12), nullable=False),
    sa.Column('new_sub_id', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['sub_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_change')
    op.drop_table('subscription')
    # ### end Alembic commands ###
